PQNLesson8ASP-CF/PQNLesson8ASP-CF/Models/PqnBookStore.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace PQNLesson8ASP_CF.Models
{
    public class PqnBookStore:DbContext
    {
        public PqnBookStore() : base()
        {

        }
        public DbSet<PqnCategory> PqnCategories { get; set; }
        public DbSet<Pqnbook> PqnBooks { get; set; }    
    }
}

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Models/PqnCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PQNLesson8ASP_CF.Models
{
    public class PqnCategory
    {
        [Key]
        public int Categoryid { get; set; }
        public string CategoryName { get; set; }

        public virtual ICollection<Pqnbook> PqnBooks { get; set; }     

    }
}

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Models/Pqnbook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PQNLesson8ASP_CF.Models
{
    public class Pqnbook
    {
        [Key]
        public int PqnBookId { get; set; }
        public string PqnBookTitle { get; set; }
        public string PqnBookAuthor { get; set; }
        public string PqnBookYear { get; set; }
        public string PqnBookPublisher { get; set; }
        public string PqnBookPicture { get; set; }
        public int PqnCategoryId { get; set;}

        public virtual PqnCategory PqnCategory  { get;set; }
    }
}

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PQNLesson8ASP_CF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PQNAbout()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Controllers/PqnBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PQNLesson8ASP_CF.Models;

namespace PqnLesson8.Controllers
{
    public class PqnBooksController : Controller
    {
        private PqnBookStore db = new PqnBookStore();


        public ActionResult PqnIndex()
        {
            return View(db.PqnBooks.ToList());
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pqnbook pqnBook = db.PqnBooks.Find(id);
            if (pqnBook == null)
            {
                return HttpNotFound();
            }
            return View(pqnBook);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pqnBookId,PqnTitle,PqnAuthor,PqnYear,pqnPublisher,PqnPicture,PqnCategoryId")] Pqnbook pqnBook)
        {
            if (ModelState.IsValid)
            {
                db.PqnBooks.Add(pqnBook);
                db.SaveChanges();
                return RedirectToAction("PqnIndex");
            }

            return View(pqnBook);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pqnbook pqnBook = db.PqnBooks.Find(id);
            if (pqnBook == null)
            {
                return HttpNotFound();
            }
            return View(pqnBook);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PqnBookId,PqnTitle,PqnAuthor,PqnYear,PqnPublisher,PqnPicture,PqnCategoryId")] Pqnbook pqnBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pqnBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PqnIndex");
            }
            return View(pqnBook);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pqnbook pqnBook = db.PqnBooks.Find(id);
            if (pqnBook == null)
            {
                return HttpNotFound();
            }
            return View(pqnBook);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pqnbook pqnBook = db.PqnBooks.Find(id);
            db.PqnBooks.Remove(pqnBook);
            db.SaveChanges();
            return RedirectToAction("PqnIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Controllers/PqnCategoryController.cs
using PQNLesson8ASP_CF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PqntLesson8.Controllers
{
    public class PqnCategoryController : Controller
    {
        private static PqnBookStore _PqnbookStore;
        public PqnCategoryController()
        {
            _PqnbookStore = new PqnBookStore();
        }

        public ActionResult PqnIndex()
        {
            var pqnCategory = _PqnbookStore.PqnCategories.ToList();
            return View(pqnCategory);
        }
        public ActionResult PqnCreate()
        {
            var PqnCategory = new PqnCategory();
            return View();
        }
        [HttpPost]
        public ActionResult PqnCreate(PqnCategory pqnCategory)
        {
            _PqnbookStore.PqnCategories.Add(pqnCategory);
            _PqnbookStore.SaveChanges();
            return RedirectToAction("PqnIndex");
        }
    }
}

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Views/Home/PQNAbout.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
    <pre>
        Mã Sinh Viên:
        Họ Tên: Phạm Quang Nhất
        Ngày Sinh:21/05/2004
        Điện Thoại:0817842585
        Email:phamquangnhatdz2105@gmail.com
    </pre>
</main>

PQNLesson8ASP-CF/PQNLesson8ASP-CF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Phạm Quang Nhất</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Phạm Quang Nhất", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pqn: Ds Categoruy", "PqnIndex", "PqnCategory", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pqn: Ds Books", "PqnIndex", "PqnBooks", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Phạm Quang Nhất</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>